=head1 NAME

AnyEvent::Filesys::Watch::Backend::FSEvents - MacOS file system watcher

=head1 SYNOPSIS

	die "AnyEvent::Filesys::Watch::Backend::FSEvents should not be used"
	    . " directly. Use AnyEvent::Filesys::Watch instead";

=head1 DESCRIPTION

This is the Mac OS backend for L<AnyEvent::Filesys::Watch>.  It uses
L<Mac::FSEvents> internally.

=head1 CONSTRUCTORS

The following constructors are available:

=over 4

=item B<new(WATCH)>

Returns the watcher. B<WATCH> should be the calling
L<AnyEvent::Filesys::Watch>.

=back

=head1 SEE ALSO

L<Mac::FSEvents>, L<AnyEvent::Filesys::Watch>, perl(1)
