name: Perl with Dist::Zilla CI (Linux)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        perl-version:
        - '5.36'
        - '5.34'
        - '5.14'

    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}

    steps:
    - name: 'Check out repository'
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: 'Perl version'
      run: perl -V

    - name: 'Installing dependencies'
      run: cpanm --notest --installdeps --verbose .

    - name: 'Build'
      run: perl Makefile.PL
      run: make

    - name: 'Test'
      run: prove -wlvmb t


    
