=head1 NAME

AnyEvent::Filesys::Watcher::Backend::Inotify2 - Linux file system watcher

=head1 SYNOPSIS

	die "AnyEvent::Filesys::Watcher::Backend::Inotify2 should not be used"
	    . " directly. Use AnyEvent::Filesys::Watcher instead";

=head1 DESCRIPTION

This is the Linux backend for L<AnyEvent::Filesys::Watcher>.  It uses
L<Linux::Inotify2> internally.

=head1 CONSTRUCTORS

The following class methods are available:

=over 4

=item B<new(WATCH)>

Returns the watcher. B<WATCH> should be the calling
L<AnyEvent::Filesys::Watcher>.

=back

=head1 SEE ALSO

L<Linux::Inotify2>, L<AnyEvent::Filesys::Watcher>, perl(1)
